import { config } from "dotenv";
import { resolve } from "path";
import { createClient } from "@supabase/supabase-js";
import { generateSlug } from "@/lib/utils/slug";

// Load .env.local file
config({ path: resolve(process.cwd(), ".env.local") });

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL!;
const supabaseKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!;

const supabase = createClient(supabaseUrl, supabaseKey);

export const seedGames = [
  {
    id: crypto.randomUUID(),
    slug: generateSlug("Two Truths and a Lie"),
    title: "Two Truths and a Lie",
    description: "A classic ice breaker where each person shares three statements about themselves - two true and one false. The group tries to guess which statement is the lie.",
    category: "Team Building",
    players: "3-20 people",
    duration: "15-20 minutes",
    difficulty: "Easy",
    materials: "None required",
    steps: "Each person thinks of two true statements and one false statement about themselves\nGo around the room, with each person sharing their three statements\nAfter each person shares, the group discusses and votes on which statement they think is the lie\nThe person reveals which statement was false\nContinue until everyone has had a turn",
    tags: ["getting-to-know-you", "no-prep", "indoor", "virtual-friendly", "students", "high-school", "college", "classroom", "non-cheesy"],
    image: null,
  },
  {
    id: crypto.randomUUID(),
    slug: generateSlug("Human Bingo"),
    title: "Human Bingo",
    description: "Participants receive bingo cards with various characteristics or experiences in each square. They must find people who match each description and get their signatures.",
    category: "Social Event",
    players: "10-50 people",
    duration: "20-30 minutes",
    difficulty: "Easy",
    materials: "Bingo cards, pens",
    steps: "Create bingo cards with different characteristics in each square\nDistribute cards and pens to all participants\nSet a time limit (usually 15-20 minutes)\nParticipants mingle and find people who match each square\nFirst person to complete a line shouts Bingo\nVerify the winner's card",
    tags: ["networking", "large-group", "active", "customizable", "students", "classroom", "high-school", "college", "orientation", "first-day"],
    image: null,
  },
  {
    id: crypto.randomUUID(),
    slug: generateSlug("Virtual Background Story"),
    title: "Virtual Background Story",
    description: "Perfect for online meetings, participants choose creative or unusual virtual backgrounds and share the story behind their choice.",
    category: "Virtual Meeting",
    players: "5-30 people",
    duration: "10-15 minutes",
    difficulty: "Easy",
    materials: "Video conferencing software with virtual background feature",
    steps: "Before the meeting, ask participants to select an interesting virtual background\nAt the start of the meeting, go around and have each person share their background\nEach person explains why they chose that particular background\nEncourage questions and comments from the group\nOptionally vote on the most creative background",
    tags: ["virtual", "creative", "remote-work", "quick", "students", "online", "classroom", "college"],
    image: null,
  },
  {
    id: crypto.randomUUID(),
    slug: generateSlug("Speed Networking"),
    title: "Speed Networking",
    description: "Participants pair up for quick one-on-one conversations, then rotate to meet new people. Great for conferences and large networking events.",
    category: "Conference",
    players: "10-100 people",
    duration: "30-45 minutes",
    difficulty: "Medium",
    materials: "Timer or bell, name tags",
    steps: "Arrange chairs in two rows facing each other\nAssign participants to seats\nSet a timer for 3-5 minutes per conversation\nRing a bell when time is up\nThe rotating row moves one seat to the right\nRepeat until everyone has met\nOptionally provide conversation prompts",
    tags: ["networking", "structured", "large-group", "professional", "students", "college", "orientation"],
    image: null,
  },
  {
    id: crypto.randomUUID(),
    slug: generateSlug("The Name Game"),
    title: "The Name Game",
    description: "A memory game where each person says their name along with an adjective that starts with the same letter. Helps with name retention in new groups.",
    category: "Classroom",
    players: "5-25 people",
    duration: "10-20 minutes",
    difficulty: "Medium",
    materials: "None required",
    steps: "Arrange participants in a circle\nFirst person says an adjective and name (e.g. Jolly John)\nSecond person repeats the first, then adds their own\nEach person repeats all previous names before adding theirs\nIf someone forgets, the group can help\nContinue until everyone has introduced themselves",
    tags: ["memory", "names", "circle-game", "educational"],
    image: null,
  },
  {
    id: crypto.randomUUID(),
    slug: generateSlug("Desert Island Scenario"),
    title: "Desert Island Scenario",
    description: "Participants imagine they're stranded on a desert island and must choose three items to bring. Reveals personality traits and priorities.",
    category: "Team Building",
    players: "4-20 people",
    duration: "15-25 minutes",
    difficulty: "Easy",
    materials: "None required",
    steps: "Explain the scenario: stranded on a desert island\nEach person chooses three items to bring\nGive participants 2-3 minutes to think\nGo around the group with each person sharing their choices\nEncourage questions and discussion\nOptionally vote on most creative choices",
    tags: ["hypothetical", "discussion", "creative-thinking", "no-prep"],
    image: null,
  },
  {
    id: crypto.randomUUID(),
    slug: generateSlug("One Word Check-In"),
    title: "One Word Check-In",
    description: "A quick activity where each person shares one word that describes how they're feeling. Perfect for starting meetings or training sessions.",
    category: "Training",
    players: "3-30 people",
    duration: "5-10 minutes",
    difficulty: "Easy",
    materials: "None required",
    steps: "Explain that each person will share just one word\nOptionally provide a prompt\nGo around the room or call on people randomly\nEach person says their one word\nAfter everyone has shared, discuss patterns or themes\nKeep it moving quickly",
    tags: ["quick", "emotional-intelligence", "check-in", "simple", "students", "classroom", "first-day", "shy-students", "low-prep"],
    image: null,
  },
  {
    id: crypto.randomUUID(),
    slug: generateSlug("Find Your Match"),
    title: "Find Your Match",
    description: "Participants receive cards with one half of a famous pair. They must find their matching partner by asking questions without directly stating what's on their card.",
    category: "Social Event",
    players: "10-50 people",
    duration: "15-20 minutes",
    difficulty: "Medium",
    materials: "Cards with famous pairs written on them",
    steps: "Prepare cards with famous pairs\nDistribute one card to each participant\nExplain they cannot directly say what's on their card\nParticipants mingle and ask yes/no questions\nOnce pairs find each other, they sit down together\nHave pairs introduce themselves",
    tags: ["active", "pairing", "large-group", "fun"],
    image: null,
  },
  {
    id: crypto.randomUUID(),
    slug: generateSlug("Show and Tell"),
    title: "Show and Tell",
    description: "Participants bring an object that's meaningful to them and share its story. Creates deeper connections and reveals personal values.",
    category: "Team Building",
    players: "4-15 people",
    duration: "20-40 minutes",
    difficulty: "Easy",
    materials: "Personal items brought by participants",
    steps: "Ask participants to bring one meaningful object\nExplain each person has 2-3 minutes to share\nGo around the group with each person presenting\nEncourage them to explain why it's meaningful\nAllow time for questions after each presentation\nOptionally vote on most interesting story",
    tags: ["personal", "storytelling", "meaningful", "virtual-friendly", "students", "classroom", "elementary", "middle-school"],
    image: null,
  },
  {
    id: crypto.randomUUID(),
    slug: generateSlug("Would You Rather"),
    title: "Would You Rather",
    description: "Participants answer a series of Would you rather questions, choosing between two options. Reveals preferences and sparks fun debates.",
    category: "Classroom",
    players: "5-50 people",
    duration: "10-20 minutes",
    difficulty: "Easy",
    materials: "List of Would you rather questions",
    steps: "Prepare a list of questions\nDesignate two sides of the room for each option\nRead the first question with two options\nParticipants move to the side representing their choice\nAsk people from each side to explain their reasoning\nContinue with remaining questions",
    tags: ["decision-making", "active", "debate", "adaptable"],
    image: null,
  },
  {
    id: crypto.randomUUID(),
    slug: generateSlug("Emoji Introduction"),
    title: "Emoji Introduction",
    description: "Participants introduce themselves using only emojis. Others try to guess what the emojis represent. A modern, visual twist on introductions.",
    category: "Virtual Meeting",
    players: "5-30 people",
    duration: "10-15 minutes",
    difficulty: "Easy",
    materials: "Chat function or paper and markers",
    steps: "Ask participants to think of 3-5 emojis that represent them\nHave each person post their emojis in the chat\nGo through each person's emojis one at a time\nThe group tries to guess what each emoji represents\nThe person explains the meaning behind their choices\nContinue until everyone has shared",
    tags: ["virtual", "creative", "modern", "visual", "students", "online", "classroom", "low-prep"],
    image: null,
  },
  {
    id: crypto.randomUUID(),
    slug: generateSlug("Common Ground"),
    title: "Common Ground",
    description: "Small groups work together to find things they all have in common. Builds team cohesion and reveals unexpected connections.",
    category: "Team Building",
    players: "8-40 people",
    duration: "15-25 minutes",
    difficulty: "Medium",
    materials: "Paper and pens for each group",
    steps: "Divide participants into groups of 4-6 people\nGive each group paper and a pen\nSet a timer for 10 minutes\nGroups find as many things as possible that everyone has in common\nExclude obvious things\nGroups share their most interesting commonalities\nOptionally award prizes",
    tags: ["small-groups", "discovery", "team-bonding", "competitive", "students", "classroom", "shy-students", "college"],
    image: null,
  },
  {
    id: crypto.randomUUID(),
    slug: generateSlug("The Question Web"),
    title: "The Question Web",
    description: "Using a ball of yarn, participants toss it to each other while asking questions. The yarn creates a physical web showing connections between people.",
    category: "Training",
    players: "8-25 people",
    duration: "20-30 minutes",
    difficulty: "Medium",
    materials: "Ball of yarn or string",
    steps: "Have participants stand in a circle\nGive the ball of yarn to one person\nThat person holds the end and asks someone else a question\nThey toss the ball while holding their section of yarn\nThe receiver answers and asks a new question\nContinue until everyone is included\nDiscuss how the web represents connections",
    tags: ["visual", "metaphor", "circle-game", "symbolic"],
    image: null,
  },
  {
    id: crypto.randomUUID(),
    slug: generateSlug("Scavenger Hunt"),
    title: "Scavenger Hunt",
    description: "Participants race to find specific items or complete challenges within a time limit. Promotes teamwork, creativity, and friendly competition.",
    category: "Conference",
    players: "10-100 people",
    duration: "30-60 minutes",
    difficulty: "Hard",
    materials: "List of items/challenges, prizes",
    steps: "Create a list of items to find or challenges to complete\nDivide participants into teams of 3-5 people\nDistribute the scavenger hunt list\nSet clear boundaries and time limit\nTeams work together to find items\nTeams document their finds with photos\nReconvene and review submissions\nDeclare a winner and award prizes",
    tags: ["active", "team-based", "competitive", "outdoor", "students", "classroom", "orientation", "large-group"],
    image: null,
  },
  {
    id: crypto.randomUUID(),
    slug: generateSlug("Appreciation Circle"),
    title: "Appreciation Circle",
    description: "Participants sit in a circle and take turns sharing something they appreciate about others. Creates a positive atmosphere and strengthens relationships.",
    category: "Team Building",
    players: "5-20 people",
    duration: "15-30 minutes",
    difficulty: "Easy",
    materials: "None required",
    steps: "Arrange participants in a circle\nExplain each person will share an appreciation\nStart with one person sharing about the person to their right\nThat person then shares about the person to their right\nContinue around the circle\nAlternatively use random order\nKeep comments genuine and specific\nEnd with a moment of reflection",
    tags: ["positive", "gratitude", "emotional", "team-bonding"],
    image: null,
  },
  {
    id: crypto.randomUUID(),
    slug: generateSlug("Line-Up"),
    title: "Line-Up",
    description: "A non-verbal ordering challenge where participants silently arrange themselves by a given criterion, building focus, teamwork, and observational communication.",
    category: "Team Building",
    players: "10-40 people",
    duration: "5-15 minutes",
    difficulty: "Easy",
    materials: "None required",
    steps: "Step 1: Explain non-verbal rule.\nStep 2: Announce a criterion (e.g., height, tenure).\nStep 3: Participants silently form an ordered line.\nStep 4: Debrief on strategies and signals.",
    tags: ["non-verbal", "collaboration", "quick", "large-group", "students", "classroom", "high-school", "non-cheesy", "low-prep"],
    image: null,
  },
  {
    id: crypto.randomUUID(),
    slug: generateSlug("Rock Paper Scissors Tournament"),
    title: "Rock Paper Scissors Tournament",
    description: "A high-energy elimination bracket using Rock–Paper–Scissors, where losers become fans who cheer for winners, quickly energizing any group.",
    category: "Team Building",
    players: "8-200+ people",
    duration: "5-10 minutes",
    difficulty: "Easy",
    materials: "None required",
    steps: "Step 1: Pair participants and play quick rounds.\nStep 2: Losers become fans of their winner.\nStep 3: Match winners until two finalists remain.\nStep 4: Run the final match and celebrate.",
    tags: ["energizer", "competition", "fun", "large-group"],
    image: null,
  },
  {
    id: crypto.randomUUID(),
    slug: generateSlug("Take a Picture of Your Shoes"),
    title: "Take a Picture of Your Shoes",
    description: "Participants share a photo of their shoes and a brief story, creating quick personal connections and light humor in virtual or hybrid meetings.",
    category: "Virtual Meeting",
    players: "5-30 people",
    duration: "5-10 minutes",
    difficulty: "Easy",
    materials: "Camera or phone; shared chat/board",
    steps: "Step 1: Ask everyone to snap and share shoe photos.\nStep 2: Invite short stories behind the shoes.\nStep 3: Optional voting on fun or unique pairs.",
    tags: ["storytelling", "remote-friendly", "quick", "check-in"],
    image: null,
  },
  {
    id: crypto.randomUUID(),
    slug: generateSlug("Near and Far"),
    title: "Near and Far",
    description: "A movement-based warm-up where participants position themselves near or far from prompts, sparking discussion on group dynamics, assumptions, and perspectives.",
    category: "Classroom",
    players: "10-50 people",
    duration: "10-20 minutes",
    difficulty: "Easy",
    materials: "Open space; prompts",
    steps: "Step 1: Present a prompt (viewpoint or experience).\nStep 2: Participants position themselves physically near or far.\nStep 3: Invite reflections and observations.\nStep 4: Debrief on assumptions and communication.",
    tags: ["reflection", "movement", "culture", "discussion"],
    image: null,
  },
  {
    id: crypto.randomUUID(),
    slug: generateSlug("Icebreaker Bingo"),
    title: "Icebreaker Bingo",
    description: "Players mingle to find colleagues who match prompts on Bingo squares; first to complete a line wins, encouraging conversation and rapid introductions.",
    category: "Team Building",
    players: "12-100+ people",
    duration: "10-20 minutes",
    difficulty: "Easy",
    materials: "Bingo cards; pens; optional prizes",
    steps: "Step 1: Distribute cards with personal prompts.\nStep 2: Mingle to find matches and mark squares.\nStep 3: Recognize first Bingo; continue as desired.\nStep 4: Optional blackout or multiple rounds.",
    tags: ["mixer", "large-group", "prizes", "quick", "students", "college", "orientation", "first-day"],
    image: null,
  },
  {
    id: crypto.randomUUID(),
    slug: generateSlug("Six Word Memoirs"),
    title: "Six Word Memoirs",
    description: "Each participant summarizes their life in six words, then shares and discusses choices, sparking curiosity and deeper conversation.",
    category: "Team Building",
    players: "4-30 people",
    duration: "10-15 minutes",
    difficulty: "Easy",
    materials: "Paper or shared doc",
    steps: "Step 1: Explain the six-word constraint.\nStep 2: Quietly draft six-word memoirs.\nStep 3: Share and discuss why those words.\nStep 4: Optional small-group breakout shares.",
    tags: ["storytelling", "reflection", "conversation", "quick"],
    image: null,
  },
  {
    id: crypto.randomUUID(),
    slug: generateSlug("Guess Who (Personal Trivia)"),
    title: "Guess Who (Personal Trivia)",
    description: "Players submit unique facts; the group guesses the author of each fact, building curiosity, rapport, and quick personal connections.",
    category: "Team Building",
    players: "8-40 people",
    duration: "10-20 minutes",
    difficulty: "Easy",
    materials: "Paper; bowl; pens",
    steps: "Step 1: Each player writes 1–3 unique facts and folds.\nStep 2: Draw a fact and read it aloud.\nStep 3: Group guesses the author; reveal and discuss.\nStep 4: Continue until all facts are revealed.",
    tags: ["curiosity", "mixer", "fun", "get-to-know"],
    image: null,
  },
  {
    id: crypto.randomUUID(),
    slug: generateSlug("Wheel of Fortune Introductions"),
    title: "Wheel of Fortune Introductions",
    description: "Use a virtual wheel with fun prompts; participants spin and answer, fostering playful introductions and engagement.",
    category: "Virtual Meeting",
    players: "6-50 people",
    duration: "8-15 minutes",
    difficulty: "Easy",
    materials: "Virtual wheel tool; prompt list",
    steps: "Step 1: Prepare a wheel with intro prompts.\nStep 2: Participants spin and answer the prompt.\nStep 3: Keep turns short to maintain pace.",
    tags: ["engagement", "fun", "prompt", "intro"],
    image: null,
  },
  {
    id: crypto.randomUUID(),
    slug: generateSlug("Where Do We Come From & What Is Famous?"),
    title: "Where Do We Come From & What Is Famous?",
    description: "Participants share hometowns or backgrounds and what’s famous there, building cultural awareness and personal connection.",
    category: "Conference",
    players: "6-50 people",
    duration: "10-20 minutes",
    difficulty: "Easy",
    materials: "Map or slides (optional)",
    steps: "Step 1: Invite each person to share their hometown.\nStep 2: Describe what the place is known for.\nStep 3: Optional: pin locations on a shared map.",
    tags: ["culture", "stories", "mixer", "map"],
    image: null,
  },
  {
    id: crypto.randomUUID(),
    slug: generateSlug("Fantasy Vacation"),
    title: "Fantasy Vacation",
    description: "Participants share dream travel destinations and activities, discovering interests and sparking conversation.",
    category: "Social Event",
    players: "4-30 people",
    duration: "8-15 minutes",
    difficulty: "Easy",
    materials: "None required",
    steps: "Step 1: Ask for dream vacation spots.\nStep 2: Share activities or itineraries.\nStep 3: Optional: vote on most creative plan.",
    tags: ["travel", "creative", "discussion", "fun"],
    image: null,
  },
  {
    id: crypto.randomUUID(),
    slug: generateSlug("Mystery Envelope"),
    title: "Mystery Envelope",
    description: "Surprise prompts or mini-challenges are drawn from envelopes; participants discuss or act them out to spark laughs and interaction.",
    category: "Conference",
    players: "6-50 people",
    duration: "10-15 minutes",
    difficulty: "Easy",
    materials: "Envelopes; printed prompts",
    steps: "Step 1: Prepare envelopes with prompts.\nStep 2: Participants draw and complete the prompt.\nStep 3: Keep rounds fast; encourage reactions.",
    tags: ["surprise", "prompt", "fun", "engagement"],
    image: null,
  },
  {
    id: crypto.randomUUID(),
    slug: generateSlug("The Check-In"),
    title: "The Check-In",
    description: "A brief emotional or energy check-in where participants share how they feel, helping teams arrive and align.",
    category: "Social Event",
    players: "3-20 people",
    duration: "5-10 minutes",
    difficulty: "Easy",
    materials: "None required",
    steps: "Step 1: Invite one-word or short check-ins.\nStep 2: Optionally use a mood scale or emojis.\nStep 3: Acknowledge and proceed with agenda.",
    tags: ["check-in", "alignment", "wellbeing", "quick"],
    image: null,
  },
  {
    id: crypto.randomUUID(),
    slug: generateSlug("Team Superpower Collage"),
    title: "Team Superpower Collage",
    description: "Participants create a visual collage showing imagined team superpowers, boosting creativity and identity.",
    category: "Training",
    players: "6-25 people",
    duration: "15-25 minutes",
    difficulty: "Easy",
    materials: "Whiteboard; images; stickers",
    steps: "Step 1: Explain superpower theme.\nStep 2: Collaboratively add images/notes to a collage.\nStep 3: Share and discuss themes.",
    tags: ["creative", "visual", "team-identity", "collaboration"],
    image: null,
  },
  {
    id: crypto.randomUUID(),
    slug: generateSlug("Invention Pitch"),
    title: "Invention Pitch",
    description: "Small groups pitch playful inventions to judges, encouraging creativity, storytelling, and persuasive skills.",
    category: "Training",
    players: "6-30 people",
    duration: "15-25 minutes",
    difficulty: "Medium",
    materials: "Timer; prompt cards",
    steps: "Step 1: Form small teams and assign prompts.\nStep 2: Prepare quick invention pitches.\nStep 3: Present; allow brief Q&A; optional voting.",
    tags: ["pitch", "creativity", "storytelling", "competition"],
    image: null,
  },
  {
    id: crypto.randomUUID(),
    slug: generateSlug("Skribbl (Pictionary Online)"),
    title: "Skribbl (Pictionary Online)",
    description: "An online drawing-and-guessing game that builds quick thinking and teamwork in remote settings.",
    category: "Virtual Meeting",
    players: "4-12 people",
    duration: "10-20 minutes",
    difficulty: "Easy",
    materials: "Skribbl or similar tool",
    steps: "Step 1: Open a shared drawing room.\nStep 2: Take turns drawing words; others guess.\nStep 3: Keep rounds short; rotate quickly.",
    tags: ["remote-friendly", "drawing", "guessing", "fun"],
    image: null,
  },
  {
    id: crypto.randomUUID(),
    slug: generateSlug("This or That Questions"),
    title: "This or That Questions",
    description: "Quick binary-choice prompts (this or that) to reveal preferences and warm up discussion.",
    category: "Social Event",
    players: "4-50 people",
    duration: "5-10 minutes",
    difficulty: "Easy",
    materials: "Prompt list",
    steps: "Step 1: Share quick pairs (e.g., coffee or tea).\nStep 2: Participants choose and explain briefly.\nStep 3: Keep pace brisk; rotate prompts.",
    tags: ["preferences", "quick", "discussion", "intro", "students", "classroom", "online", "shy-students", "low-prep"],
    image: null,
  },
  {
    id: crypto.randomUUID(),
    slug: generateSlug("Guess Who"),
    title: "Guess Who",
    description: "Participants submit quirky facts; the group guesses who each fact belongs to, encouraging curiosity and interaction.",
    category: "Social Event",
    players: "6-40 people",
    duration: "10-20 minutes",
    difficulty: "Easy",
    materials: "Paper or form; bowl",
    steps: "Step 1: Collect one quirky fact per person.\nStep 2: Draw and read facts; group guesses.\nStep 3: Reveal and briefly discuss.",
    tags: ["curiosity", "mixer", "fun", "get-to-know"],
    image: null,
  },
  {
    id: crypto.randomUUID(),
    slug: generateSlug("Never Have I Ever"),
    title: "Never Have I Ever",
    description: "Participants share things they’ve never done; others indicate if they have, creating light-hearted discovery.",
    category: "Social Event",
    players: "6-30 people",
    duration: "10-15 minutes",
    difficulty: "Easy",
    materials: "None required",
    steps: "Step 1: Share a \"Never have I ever...\" statement.\nStep 2: Indicate if done (raise hand, emoji).\nStep 3: Optional: share brief stories.",
    tags: ["fun", "mixer", "stories", "quick"],
    image: null,
  },
  {
    id: crypto.randomUUID(),
    slug: generateSlug("Story Swap"),
    title: "Story Swap",
    description: "Pairs exchange short personal stories using visual prompts, building trust, listening, and creativity.",
    category: "Social Event",
    players: "6-40 people",
    duration: "10-15 minutes",
    difficulty: "Easy",
    materials: "Prompt cards or images",
    steps: "Step 1: Form pairs and provide visual prompts.\nStep 2: Partner A shares a brief story; Partner B listens.\nStep 3: Swap roles; optional group share.",
    tags: ["storytelling", "pairs", "listening", "creative"],
    image: null,
  },
  {
    id: crypto.randomUUID(),
    slug: generateSlug("If Then"),
    title: "If Then",
    description: "Participants complete playful \"If I were..., then I would...\" prompts to spark imagination and rapport.",
    category: "Social Event",
    players: "5-30 people",
    duration: "8-12 minutes",
    difficulty: "Easy",
    materials: "Prompt list",
    steps: "Step 1: Share \"If/Then\" prompts (e.g., If I were a city...).\nStep 2: Participants answer and briefly explain.\nStep 3: Optional: small-group rounds or voting.",
    tags: ["creative", "prompt", "fun", "intro"],
    image: null,
  },
  {
    id: crypto.randomUUID(),
    slug: generateSlug("Crossword Names"),
    title: "Crossword Names",
    description: "Create a name \"crossword\" by intersecting letters of participants’ names, helping name recall and connection.",
    category: "Social Event",
    players: "8-30 people",
    duration: "10-15 minutes",
    difficulty: "Easy",
    materials: "Large paper or whiteboard; markers",
    steps: "Step 1: Write a name; add other names intersecting shared letters.\nStep 2: Invite each person to introduce themselves as they add.\nStep 3: Review the grid together.",
    tags: ["names", "visual", "group-intro", "creative"],
    image: null,
  },
  {
    id: crypto.randomUUID(),
    slug: generateSlug("Blind Name-Tag"),
    title: "Blind Name-Tag",
    description: "Wear name-tags on backs; mingle and guess identities with clues, creating laughter and quick intros.",
    category: "Social Event",
    players: "8-40 people",
    duration: "10-15 minutes",
    difficulty: "Easy",
    materials: "Name tags; markers",
    steps: "Step 1: Place each person’s name-tag on their back.\nStep 2: Mingle and ask yes/no questions to guess your name.\nStep 3: Reveal and do quick introductions.",
    tags: ["names", "mixer", "fun", "movement"],
    image: null,
  },
  {
    id: crypto.randomUUID(),
    slug: generateSlug("Dicebreakers"),
    title: "Dicebreakers",
    description: "Roll a die to select conversation prompts; share brief responses to build meaningful connections.",
    category: "Social Event",
    players: "4-30 people",
    duration: "8-12 minutes",
    difficulty: "Easy",
    materials: "Dice; prompt list (1–6)",
    steps: "Step 1: Assign prompts to numbers 1–6.\nStep 2: Roll and answer the matching prompt.\nStep 3: Rotate quickly; encourage follow-up questions.",
    tags: ["prompt", "conversation", "quick", "fun"],
    image: null,
  },
  {
    id: crypto.randomUUID(),
    slug: generateSlug("Motion Name-Game"),
    title: "Motion Name-Game",
    description: "Learn names with a unique motion attached to each person, reinforcing memory through movement.",
    category: "Social Event",
    players: "8-30 people",
    duration: "8-12 minutes",
    difficulty: "Easy",
    materials: "Open space",
    steps: "Step 1: Stand in a circle; each person states name with a motion.\nStep 2: Group repeats name and motion in sequence.\nStep 3: Build the sequence around the circle.",
    tags: ["names", "movement", "memory", "energizer"],
    image: null,
  },
  {
    id: crypto.randomUUID(),
    slug: generateSlug("Sole Mate"),
    title: "Sole Mate",
    description: "Quick partner-matching game using simple tokens or halves to form random pairs for activities.",
    category: "Social Event",
    players: "10-60 people",
    duration: "5-8 minutes",
    difficulty: "Easy",
    materials: "Matching tokens or card halves",
    steps: "Step 1: Distribute paired tokens/halves.\nStep 2: Mingle to find your matching \"sole mate\".\nStep 3: Pair up and proceed to next activity.",
    tags: ["pairs", "quick", "mixer", "randomize"],
    image: null,
  },
  {
    id: crypto.randomUUID(),
    slug: generateSlug("Year Of The Coin"),
    title: "Year Of The Coin",
    description: "Draw a coin with a year; share a memory from that year to spark stories and connection.",
    category: "Social Event",
    players: "4-30 people",
    duration: "8-12 minutes",
    difficulty: "Easy",
    materials: "Jar of coins or printed years",
    steps: "Step 1: Each person draws a coin/year.\nStep 2: Share a memory or story linked to that year.\nStep 3: Encourage brief follow-ups; rotate.",
    tags: ["stories", "reflection", "prompt", "quick"],
    image: null,
  },
  {
    id: crypto.randomUUID(),
    slug: generateSlug("Name That Movie Quote"),
    title: "Name That Movie Quote",
    description: "Quote a line from a movie; the group guesses the film, creating playful competition and shared references.",
    category: "Social Event",
    players: "4-30 people",
    duration: "8-12 minutes",
    difficulty: "Easy",
    materials: "None required",
    steps: "Step 1: Participants take turns quoting a movie line.\nStep 2: Group guesses the movie.\nStep 3: Optional: keep score or themed rounds.",
    tags: ["fun", "competition", "pop-culture", "quick"],
    image: null,
  },
  {
    id: crypto.randomUUID(),
    slug: generateSlug("10 Things in Common"),
    title: "10 Things in Common",
    description: "Pairs find ten commonalities beyond the obvious, encouraging conversation and discovery.",
    category: "Social Event",
    players: "6-50 people",
    duration: "8-12 minutes",
    difficulty: "Easy",
    materials: "None required",
    steps: "Step 1: Pair up participants.\nStep 2: Find and list ten things in common.\nStep 3: Optional: share top 3 with the group.",
    tags: ["pairs", "conversation", "mixer", "quick"],
    image: null,
  },
  {
    id: crypto.randomUUID(),
    slug: generateSlug("Guess That Team Member"),
    title: "Guess That Team Member",
    description: "Read anonymous facts and guess who they belong to, building curiosity and fun discovery.",
    category: "Social Event",
    players: "6-40 people",
    duration: "10-15 minutes",
    difficulty: "Easy",
    materials: "Paper strips or form; bowl",
    steps: "Step 1: Collect 5 facts per person anonymously.\nStep 2: Read facts; group guesses the person.\nStep 3: Reveal and briefly discuss.",
    tags: ["curiosity", "mixer", "get-to-know", "fun"],
    image: null,
  },
  {
    id: crypto.randomUUID(),
    slug: generateSlug("Skittles Sharing"),
    title: "Skittles Sharing",
    description: "Assign prompts to candy colors; participants answer based on colors they pick, encouraging varied sharing.",
    category: "Social Event",
    players: "6-40 people",
    duration: "8-12 minutes",
    difficulty: "Easy",
    materials: "Skittles or M&M’s; prompt key",
    steps: "Step 1: Define color-to-question mapping.\nStep 2: Each person picks candies and answers prompts.\nStep 3: Optional: reveal mapping after picking.",
    tags: ["fun", "prompt", "sharing", "mixer"],
    image: null,
  },
  {
    id: crypto.randomUUID(),
    slug: generateSlug("News Headline Warm-up"),
    title: "News Headline Warm-up",
    description: "Create a catchy news headline about the meeting topic to prime brainstorming and focus.",
    category: "Social Event",
    players: "4-30 people",
    duration: "8-12 minutes",
    difficulty: "Easy",
    materials: "Sticky notes or shared doc",
    steps: "Step 1: Ask each person to write a headline for today’s topic.\nStep 2: Share and cluster similar themes.\nStep 3: Use top headlines to kick off discussion.",
    tags: ["creative", "topical", "brainstorm", "focus"],
    image: null,
  },
  {
    id: crypto.randomUUID(),
    slug: generateSlug("Two Truths and a Dream"),
    title: "Two Truths and a Dream",
    description: "A twist on \"Two truths and a lie\": share two facts and one aspiration to inspire connection.",
    category: "Social Event",
    players: "4-30 people",
    duration: "8-12 minutes",
    difficulty: "Easy",
    materials: "None required",
    steps: "Step 1: Explain the facts-plus-dream format.\nStep 2: Each person shares two truths and one dream.\nStep 3: Brief Q&A; encourage supportive reactions.",
    tags: ["get-to-know", "aspiration", "positive", "conversation"],
    image: null,
  },
  {
    id: crypto.randomUUID(),
    slug: generateSlug("Reception Line"),
    title: "Reception Line",
    description: "Two facing lines answer quick prompts and rotate, enabling fast-paced introductions and sharing.",
    category: "Social Event",
    players: "10-50 people",
    duration: "10-15 minutes",
    difficulty: "Easy",
    materials: "Prompt list; timer",
    steps: "Step 1: Form two facing lines.\nStep 2: Ask a question; pairs share briefly.\nStep 3: Rotate and repeat with new prompts.",
    tags: ["mixer", "rotation", "quick", "intro"],
    image: null,
  },
  {
    id: crypto.randomUUID(),
    slug: generateSlug("Runners (Seer–Runner–Builder)"),
    title: "Runners (Seer–Runner–Builder)",
    description: "A communication relay: Seer describes, Runner transmits, Builder constructs. Highlights clarity and teamwork.",
    category: "Team Building",
    players: "6-24 people",
    duration: "15-20 minutes",
    difficulty: "Medium",
    materials: "Building supplies; sample model",
    steps: "Step 1: Assign roles: Seer, Runner, Builder.\nStep 2: Seer views model and instructs Runner (limited rules).\nStep 3: Runner relays to Builder; iterate to match model.",
    tags: ["communication", "roles", "problem-solving", "iteration"],
    image: null,
  },
  {
    id: crypto.randomUUID(),
    slug: generateSlug("Category Mixer"),
    title: "Category Mixer",
    description: "Call out a category; participants mingle to find others who match, then share mini-stories.",
    category: "Social Event",
    players: "10-60 people",
    duration: "8-12 minutes",
    difficulty: "Easy",
    materials: "Category list",
    steps: "Step 1: Announce a category (e.g., favorite sport).\nStep 2: Find others who match and cluster.\nStep 3: Share quick stories in clusters.",
    tags: ["movement", "mixer", "fun", "quick"],
    image: null,
  },
  {
    id: crypto.randomUUID(),
    slug: generateSlug("Paper Bag Pickup"),
    title: "Paper Bag Pickup",
    description: "A playful balance challenge: pick up a paper bag from the floor without using hands on the ground.",
    category: "Social Event",
    players: "6-30 people",
    duration: "8-12 minutes",
    difficulty: "Easy",
    materials: "Paper bag",
    steps: "Step 1: Place a bag on the floor.\nStep 2: Take turns trying to pick it up using only your mouth.\nStep 3: Trim bag height to increase difficulty.",
    tags: ["balance", "fun", "competition", "energizer"],
    image: null,
  },
  {
    id: crypto.randomUUID(),
    slug: generateSlug("Telephone Charades"),
    title: "Telephone Charades",
    description: "Blend of telephone and charades: act a prompt down a line; last person guesses, often hilariously.",
    category: "Social Event",
    players: "10-40 people",
    duration: "10-15 minutes",
    difficulty: "Easy",
    materials: "Prompt list",
    steps: "Step 1: Form two lines; give end players prompts.\nStep 2: Act and pass the prompt down the line.\nStep 3: Final players guess the original prompt.",
    tags: ["hilarious", "movement", "team", "guessing"],
    image: null,
  },
  {
    id: crypto.randomUUID(),
    slug: generateSlug("Marshmallow Challenge"),
    title: "Marshmallow Challenge",
    description: "Teams build the tallest spaghetti tower that can support a marshmallow, practicing prototyping and teamwork.",
    category: "Social Event",
    players: "8-40 people",
    duration: "15-25 minutes",
    difficulty: "Medium",
    materials: "Spaghetti; tape; string; marshmallow",
    steps: "Step 1: Form teams and explain constraints.\nStep 2: Prototype multiple structures quickly.\nStep 3: Measure tallest successful tower.",
    tags: ["innovation", "teamwork", "prototype", "competition"],
    image: null,
  },
  {
    id: crypto.randomUUID(),
    slug: generateSlug("Picture Sharing"),
    title: "Picture Sharing",
    description: "Share a meaningful photo to introduce hobbies, values, or aspirations; discuss briefly.",
    category: "Social Event",
    players: "4-30 people",
    duration: "8-12 minutes",
    difficulty: "Easy",
    materials: "Printed or digital photos",
    steps: "Step 1: Ask each person to pick a meaningful photo.\nStep 2: Share and explain significance.\nStep 3: Optional: Q&A or reactions.",
    tags: ["visual", "story", "empathy", "remote-friendly"],
    image: null,
  },
  {
    id: crypto.randomUUID(),
    slug: generateSlug("Would You Rather (Training)"),
    title: "Would You Rather (Training)",
    description: "Pose light dilemmas related to training context; participants choose and explain reasoning.",
    category: "Social Event",
    players: "6-50 people",
    duration: "8-12 minutes",
    difficulty: "Easy",
    materials: "Question list or poll tool",
    steps: "Step 1: Share 2-option dilemmas.\nStep 2: Vote or choose; explain briefly.\nStep 3: Optional: themed rounds.",
    tags: ["preferences", "discussion", "quick", "poll"],
    image: null,
  },
  {
    id: crypto.randomUUID(),
    slug: generateSlug("Train Wreck"),
    title: "Train Wreck",
    description: "Circle of chairs game with movement triggers; players swap seats when statements apply; high-energy mixer.",
    category: "Social Event",
    players: "12-50 people",
    duration: "10-15 minutes",
    difficulty: "Easy",
    materials: "Chairs; placeholder items",
    steps: "Step 1: Arrange chairs in a circle; mark spots.\nStep 2: Person in middle shares a statement; matching players move.\nStep 3: Call \"train wreck\" to reshuffle everyone.",
    tags: ["movement", "mixer", "fun", "large-group"],
    image: null,
  },
  {
    id: crypto.randomUUID(),
    slug: generateSlug("Human Knot"),
    title: "Human Knot",
    description: "Form a tangled circle by holding hands with two non-adjacent people; untangle without letting go.",
    category: "Team Building",
    players: "8-30 people",
    duration: "10-15 minutes",
    difficulty: "Medium",
    materials: "Open space",
    steps: "Step 1: Form a circle; grab two non-adjacent hands.\nStep 2: Work together to untangle into a circle.\nStep 3: Split into smaller groups for large teams.",
    tags: ["problem-solving", "teamwork", "movement", "fun"],
    image: null,
  },
  {
    id: crypto.randomUUID(),
    slug: generateSlug("Sing-Off"),
    title: "Sing-Off",
    description: "Teams alternate singing songs containing a theme word; eliminates repeats; everyone participates.",
    category: "Social Event",
    players: "10-60 people",
    duration: "10-15 minutes",
    difficulty: "Easy",
    materials: "Theme word list",
    steps: "Step 1: Pick a theme word (e.g., love).\nStep 2: Teams alternate singing applicable songs.\nStep 3: Eliminate repeats or skips; crown winner.",
    tags: ["music", "competition", "energizer", "fun"],
    image: null,
  },
  {
    id: crypto.randomUUID(),
    slug: generateSlug("Alliterative Name Game"),
    title: "Alliterative Name Game",
    description: "Name plus themed alliteration; sequence builds memory as each person repeats and adds.",
    category: "Social Event",
    players: "8-40 people",
    duration: "8-12 minutes",
    difficulty: "Easy",
    materials: "Theme list (optional)",
    steps: "Step 1: Choose a theme; share name + matching word.\nStep 2: Next person repeats prior and adds theirs.\nStep 3: Continue; final person recites all.",
    tags: ["names", "memory", "circle", "theme"],
    image: null,
  },
  {
    id: crypto.randomUUID(),
    slug: generateSlug("Beach Ball Q&A"),
    title: "Beach Ball Q&A",
    description: "Write questions on a beach ball; toss and answer the question near left thumb on catch.",
    category: "Social Event",
    players: "10-40 people",
    duration: "10-15 minutes",
    difficulty: "Easy",
    materials: "Beach ball; marker",
    steps: "Step 1: Write get-to-know prompts on a ball.\nStep 2: Toss; catcher answers the nearest prompt.\nStep 3: Continue tossing and sharing.",
    tags: ["movement", "fun", "prompt", "mixer"],
    image: null,
  },
  {
    id: crypto.randomUUID(),
    slug: generateSlug("Pterodactyl"),
    title: "Pterodactyl",
    description: "Say \"pterodactyl\" while hiding teeth with lips; roaring changes direction; showing teeth eliminates.",
    category: "Social Event",
    players: "8-30 people",
    duration: "8-12 minutes",
    difficulty: "Easy",
    materials: "None required",
    steps: "Step 1: Sit or stand in a circle; keep teeth covered.\nStep 2: Say \"pterodactyl\" to pass turn; roar flips direction.\nStep 3: Anyone showing teeth is out.",
    tags: ["hilarious", "circle", "quick", "energizer"],
    image: null,
  },
  {
    id: crypto.randomUUID(),
    slug: generateSlug("Telephone Charades (Lines)"),
    title: "Telephone Charades (Lines)",
    description: "Two lines act prompts down the chain; last players guess original; great for large groups.",
    category: "Social Event",
    players: "12-60 people",
    duration: "10-15 minutes",
    difficulty: "Easy",
    materials: "Prompt list",
    steps: "Step 1: Form two lines; give end players prompts.\nStep 2: Act and pass down the line.\nStep 3: Final players guess the prompt.",
    tags: ["large-group", "movement", "team", "guessing"],
    image: null,
  },
  {
    id: crypto.randomUUID(),
    slug: generateSlug("Chainlink"),
    title: "Chainlink",
    description: "Build a chain of introductions by linking to shared commonalities; fosters quick rapport.",
    category: "Social Event",
    players: "8-40 people",
    duration: "10-15 minutes",
    difficulty: "Easy",
    materials: "None required",
    steps: "Step 1: First person introduces a fact.\nStep 2: Next links with a shared trait and adds theirs.\nStep 3: Continue to build the chain across the group.",
    tags: ["common-ground", "mixer", "intro", "fun"],
    image: null,
  },
];

async function runSeed() {
  try {
    console.log("Starting to seed games using Supabase client...");
    console.log(`Supabase URL: ${supabaseUrl}`);
    
    // Check if games already exist
    const { data: existingGames, error: checkError } = await supabase
      .from("games")
      .select("id")
      .limit(1);

    if (checkError) {
      console.error("Error checking existing games:", checkError);
      throw checkError;
    }

    if (existingGames && existingGames.length > 0) {
      console.log("Games already exist in database. Skipping seed.");
      console.log("To re-seed, first delete existing games from the database.");
      return;
    }

    // Insert games
    const { data, error } = await supabase
      .from("games")
      .insert(seedGames)
      .select();

    if (error) {
      console.error("Error inserting games:", error);
      throw error;
    }

    console.log(`Successfully seeded ${seedGames.length} games!`);
    console.log("Games added:");
    seedGames.forEach((game, index) => {
      console.log(`${index + 1}. ${game.title} (${game.category})`);
    });
    
  } catch (error) {
    console.error("Error seeding games:", error);
    throw error;
  }
}

if (process.argv[1] && process.argv[1].includes("games-supabase.ts")) {
  runSeed()
    .then(() => {
      console.log("Seed completed successfully!");
      process.exit(0);
    })
    .catch((error) => {
      console.error("Seed failed:", error);
      process.exit(1);
    });
}
