-- Ice Breaker Games Seed Data
-- Run this SQL in Supabase SQL Editor to populate the games table

INSERT INTO games (id, title, description, category, players, duration, difficulty, materials, steps, tags, image, created_at, updated_at) VALUES
(gen_random_uuid(), 'Two Truths and a Lie', 'A classic ice breaker where each person shares three statements about themselves - two true and one false. The group tries to guess which statement is the lie.', 'Team Building', '3-20 people', '15-20 minutes', 'Easy', 'None required', E'Each person thinks of two true statements and one false statement about themselves\nGo around the room, with each person sharing their three statements\nAfter each person shares, the group discusses and votes on which statement they think is the lie\nThe person reveals which statement was false\nContinue until everyone has had a turn', ARRAY['getting-to-know-you', 'no-prep', 'indoor', 'virtual-friendly'], NULL, NOW(), NOW()),

(gen_random_uuid(), 'Human Bingo', 'Participants receive bingo cards with various characteristics or experiences in each square. They must find people who match each description and get their signatures.', 'Social Event', '10-50 people', '20-30 minutes', 'Easy', 'Bingo cards, pens', E'Create bingo cards with different characteristics in each square\nDistribute cards and pens to all participants\nSet a time limit (usually 15-20 minutes)\nParticipants mingle and find people who match each square\nFirst person to complete a line shouts Bingo\nVerify the winner''s card', ARRAY['networking', 'large-group', 'active', 'customizable'], NULL, NOW(), NOW()),

(gen_random_uuid(), 'Virtual Background Story', 'Perfect for online meetings, participants choose creative or unusual virtual backgrounds and share the story behind their choice.', 'Virtual Meeting', '5-30 people', '10-15 minutes', 'Easy', 'Video conferencing software with virtual background feature', E'Before the meeting, ask participants to select an interesting virtual background\nAt the start of the meeting, go around and have each person share their background\nEach person explains why they chose that particular background\nEncourage questions and comments from the group\nOptionally vote on the most creative background', ARRAY['virtual', 'creative', 'remote-work', 'quick'], NULL, NOW(), NOW()),

(gen_random_uuid(), 'Speed Networking', 'Participants pair up for quick one-on-one conversations, then rotate to meet new people. Great for conferences and large networking events.', 'Conference', '10-100 people', '30-45 minutes', 'Medium', 'Timer or bell, name tags', E'Arrange chairs in two rows facing each other\nAssign participants to seats\nSet a timer for 3-5 minutes per conversation\nRing a bell when time is up\nThe rotating row moves one seat to the right\nRepeat until everyone has met\nOptionally provide conversation prompts', ARRAY['networking', 'structured', 'large-group', 'professional'], NULL, NOW(), NOW()),

(gen_random_uuid(), 'The Name Game', 'A memory game where each person says their name along with an adjective that starts with the same letter. Helps with name retention in new groups.', 'Classroom', '5-25 people', '10-20 minutes', 'Medium', 'None required', E'Arrange participants in a circle\nFirst person says an adjective and name (e.g. Jolly John)\nSecond person repeats the first, then adds their own\nEach person repeats all previous names before adding theirs\nIf someone forgets, the group can help\nContinue until everyone has introduced themselves', ARRAY['memory', 'names', 'circle-game', 'educational'], NULL, NOW(), NOW()),

(gen_random_uuid(), 'Desert Island Scenario', 'Participants imagine they''re stranded on a desert island and must choose three items to bring. Reveals personality traits and priorities.', 'Team Building', '4-20 people', '15-25 minutes', 'Easy', 'None required', E'Explain the scenario: stranded on a desert island\nEach person chooses three items to bring\nGive participants 2-3 minutes to think\nGo around the group with each person sharing their choices\nEncourage questions and discussion\nOptionally vote on most creative choices', ARRAY['hypothetical', 'discussion', 'creative-thinking', 'no-prep'], NULL, NOW(), NOW()),

(gen_random_uuid(), 'One Word Check-In', 'A quick activity where each person shares one word that describes how they''re feeling. Perfect for starting meetings or training sessions.', 'Training', '3-30 people', '5-10 minutes', 'Easy', 'None required', E'Explain that each person will share just one word\nOptionally provide a prompt\nGo around the room or call on people randomly\nEach person says their one word\nAfter everyone has shared, discuss patterns or themes\nKeep it moving quickly', ARRAY['quick', 'emotional-intelligence', 'check-in', 'simple'], NULL, NOW(), NOW()),

(gen_random_uuid(), 'Find Your Match', 'Participants receive cards with one half of a famous pair. They must find their matching partner by asking questions without directly stating what''s on their card.', 'Social Event', '10-50 people', '15-20 minutes', 'Medium', 'Cards with famous pairs written on them', E'Prepare cards with famous pairs\nDistribute one card to each participant\nExplain they cannot directly say what''s on their card\nParticipants mingle and ask yes/no questions\nOnce pairs find each other, they sit down together\nHave pairs introduce themselves', ARRAY['active', 'pairing', 'large-group', 'fun'], NULL, NOW(), NOW()),

(gen_random_uuid(), 'Show and Tell', 'Participants bring an object that''s meaningful to them and share its story. Creates deeper connections and reveals personal values.', 'Team Building', '4-15 people', '20-40 minutes', 'Easy', 'Personal items brought by participants', E'Ask participants to bring one meaningful object\nExplain each person has 2-3 minutes to share\nGo around the group with each person presenting\nEncourage them to explain why it''s meaningful\nAllow time for questions after each presentation\nOptionally vote on most interesting story', ARRAY['personal', 'storytelling', 'meaningful', 'virtual-friendly'], NULL, NOW(), NOW()),

(gen_random_uuid(), 'Would You Rather', 'Participants answer a series of Would you rather questions, choosing between two options. Reveals preferences and sparks fun debates.', 'Classroom', '5-50 people', '10-20 minutes', 'Easy', 'List of Would you rather questions', E'Prepare a list of questions\nDesignate two sides of the room for each option\nRead the first question with two options\nParticipants move to the side representing their choice\nAsk people from each side to explain their reasoning\nContinue with remaining questions', ARRAY['decision-making', 'active', 'debate', 'adaptable'], NULL, NOW(), NOW()),

(gen_random_uuid(), 'Emoji Introduction', 'Participants introduce themselves using only emojis. Others try to guess what the emojis represent. A modern, visual twist on introductions.', 'Virtual Meeting', '5-30 people', '10-15 minutes', 'Easy', 'Chat function or paper and markers', E'Ask participants to think of 3-5 emojis that represent them\nHave each person post their emojis in the chat\nGo through each person''s emojis one at a time\nThe group tries to guess what each emoji represents\nThe person explains the meaning behind their choices\nContinue until everyone has shared', ARRAY['virtual', 'creative', 'modern', 'visual'], NULL, NOW(), NOW()),

(gen_random_uuid(), 'Common Ground', 'Small groups work together to find things they all have in common. Builds team cohesion and reveals unexpected connections.', 'Team Building', '8-40 people', '15-25 minutes', 'Medium', 'Paper and pens for each group', E'Divide participants into groups of 4-6 people\nGive each group paper and a pen\nSet a timer for 10 minutes\nGroups find as many things as possible that everyone has in common\nExclude obvious things\nGroups share their most interesting commonalities\nOptionally award prizes', ARRAY['small-groups', 'discovery', 'team-bonding', 'competitive'], NULL, NOW(), NOW()),

(gen_random_uuid(), 'The Question Web', 'Using a ball of yarn, participants toss it to each other while asking questions. The yarn creates a physical web showing connections between people.', 'Training', '8-25 people', '20-30 minutes', 'Medium', 'Ball of yarn or string', E'Have participants stand in a circle\nGive the ball of yarn to one person\nThat person holds the end and asks someone else a question\nThey toss the ball while holding their section of yarn\nThe receiver answers and asks a new question\nContinue until everyone is included\nDiscuss how the web represents connections', ARRAY['visual', 'metaphor', 'circle-game', 'symbolic'], NULL, NOW(), NOW()),

(gen_random_uuid(), 'Scavenger Hunt', 'Participants race to find specific items or complete challenges within a time limit. Promotes teamwork, creativity, and friendly competition.', 'Conference', '10-100 people', '30-60 minutes', 'Hard', 'List of items/challenges, prizes', E'Create a list of items to find or challenges to complete\nDivide participants into teams of 3-5 people\nDistribute the scavenger hunt list\nSet clear boundaries and time limit\nTeams work together to find items\nTeams document their finds with photos\nReconvene and review submissions\nDeclare a winner and award prizes', ARRAY['active', 'team-based', 'competitive', 'outdoor'], NULL, NOW(), NOW()),

(gen_random_uuid(), 'Appreciation Circle', 'Participants sit in a circle and take turns sharing something they appreciate about others. Creates a positive atmosphere and strengthens relationships.', 'Team Building', '5-20 people', '15-30 minutes', 'Easy', 'None required', E'Arrange participants in a circle\nExplain each person will share an appreciation\nStart with one person sharing about the person to their right\nThat person then shares about the person to their right\nContinue around the circle\nAlternatively use random order\nKeep comments genuine and specific\nEnd with a moment of reflection', ARRAY['positive', 'gratitude', 'emotional', 'team-bonding'], NULL, NOW(), NOW());

-- Verify the insert
SELECT COUNT(*) as total_games FROM games;
SELECT title, category FROM games ORDER BY created_at;
